USE ExameCAPDB
GO
CREATE TABLE Passageiro(
	CodigoPassageiro INT NOT NULL IDENTITY(1,1),
	Nome VARCHAR(MAX) NOT NULL,
	Email VARCHAR(MAX) NOT NULL,
	Telefone VARCHAR(MAX) NOT NULL,
	Usuario VARCHAR(MAX) NOT NULL,
	Senha VARCHAR(MAX) NOT NULL,
	Documento VARCHAR(MAX) NOT NULL,
	NumeroCartao VARCHAR(MAX) NOT NULL,
	DataNascimento DATE NOT NULL,
	Situacao BIT NULL DEFAULT(1),
	CONSTRAINT PK_Passageiro PRIMARY KEY (CodigoPassageiro),
)
GO
