DECLARE @TESTE VARCHAR(255)
SET @TESTE = '                 Testando as functions em TSQL.    -    '
SELECT @TESTE

--LEN
SELECT('@TESTE tem ' + CONVERT(VARCHAR(MAX), LEN(@TESTE)) + ' caracteres.')

--LEFT
--SELECT(LEFT(@TESTE, 5))

--RIGTH
--SELECT(RIGHT(@TESTE, 5))

--TRIM
--SELECT(TRIM(@TESTE))

--LTRIM
--SELECT(LTRIM(@TESTE))

--RTRIM
--SELECT(RTRIM(@TESTE))

--SUBSTRING
--SELECT(SUBSTRING(@TESTE, 8,20))

--SUBSTRING COM LTRIM
--SELECT(LTRIM(SUBSTRING(@TESTE, 8, 20)))

--SUBSTRING COM LTRIM E RTRIM
--SELECT(LTRIM(RTRIM(SUBSTRING(@TESTE, 8, 20))))

--LEN DO SUBSTRING COM LTRIM E RTRIM
--SELECT(LEN(LTRIM(RTRIM(SUBSTRING(@TESTE, 8, 20)))))

--LOWER
--SELECT(LOWER(@TESTE))

--UPPER
SELECT(UPPER(@TESTE))

GO
