USE [ACADEMIA]
GO

CREATE SCHEMA EST
GO

CREATE SCHEMA RH
GO

CREATE SCHEMA Geral
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [EST].[Categoria](
	[Codigo] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](max) NOT NULL,
	[DataInsert] [datetime] NOT NULL,
 CONSTRAINT [PK_Categoria] PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Geral].[Cliente](
	[Codigo] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](max) NOT NULL,
	[RazaoSocial] [varchar](max) NULL,
	[NomeFantasia] [varchar](max) NULL,
	[Documento] [varchar](14) NOT NULL,
	[Telefone] [varchar](11) NOT NULL,
	[Email] [varchar](max) NOT NULL,
	[TipoPessoa] [char](1) NOT NULL,
	[Endereco] [varchar](max) NULL,
	[Ativo] [bit] NOT NULL,
	[DataInclusao] [datetime] NOT NULL,
	[DataAlteracao] [datetime] NULL,
	[DataExclusao] [datetime] NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RH].[Departamento](
	[DepartamentoId] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](max) NOT NULL,
	[DataInsert] [datetime] NULL,
 CONSTRAINT [PK_Departamento] PRIMARY KEY CLUSTERED 
(
	[DepartamentoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Geral].[Estado](
	[CodigoUF] [int] NOT NULL,
	[SiglaUF] [char](2) NOT NULL,
	[DescricaoUF] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[CodigoUF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RH].[Funcionario](
	[FuncionarioId] [bigint] IDENTITY(1,1) NOT NULL,
	[Matricula] [bigint] NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[Sobrenome] [varchar](50) NOT NULL,
	[Sexo] [char](1) NOT NULL,
	[DataNascimento] [datetime] NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[Ctps] [varchar](20) NOT NULL,
	[CtpsNum] [bigint] NOT NULL,
	[CtpsSerie] [int] NOT NULL,
	[DataAdmissao] [datetime] NULL,
 CONSTRAINT [PK_Funcionario] PRIMARY KEY CLUSTERED 
(
	[FuncionarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Geral].[InstituicaoBancaria](
	[InstituicaoBancariaID] [int] IDENTITY(1,1) NOT NULL,
	[CodigoBanco] [int] NULL,
	[Descricao] [varchar](max) NOT NULL,
	[SiteWWW] [varchar](max) NOT NULL,
	[DataInsert] [datetime] NULL,
 CONSTRAINT [PK_InstituicaoBancaria] PRIMARY KEY CLUSTERED 
(
	[InstituicaoBancariaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Geral].[Municipio](
	[CodigoMunicipio] [int] NOT NULL,
	[NomeMunicipio] [varchar](max) NOT NULL,
	[CodigoIBGE6] [int] NOT NULL,
	[CodigoIBGE7] [int] NOT NULL,
	[CEP] [int] NOT NULL,
	[CodigoUF] [int] NOT NULL,
	[SiglaUF] [char](2) NOT NULL,
	[Regiao] [varchar](255) NOT NULL,
	[Populacao] [int] NULL,
	[Porte] [varchar](255) NULL,
	[DataInclusao] [datetime] NULL,
 CONSTRAINT [PK_Municipio] PRIMARY KEY CLUSTERED 
(
	[CodigoMunicipio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Geral].[Pais](
	[PaisID] [int] IDENTITY(1,1) NOT NULL,
	[Sigla] [varchar](3) NOT NULL,
	[CodigoIdioma] [varchar](2) NOT NULL,
	[Descricao] [varchar](max) NOT NULL,
	[DataInsert] [datetime] NULL,
 CONSTRAINT [PK_Pais] PRIMARY KEY CLUSTERED 
(
	[PaisID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [EST].[Produto](
	[Codigo] [int] IDENTITY(1,1) NOT NULL,
	[CodigoSubcategoria] [int] NOT NULL,
	[CodigoCategoria] [int] NOT NULL,
	[Descricao] [varchar](max) NOT NULL,
	[DataInsert] [datetime] NOT NULL,
 CONSTRAINT [PK_Produto] PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [RH].[Profissao](
	[ProfissaoID] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](max) NOT NULL,
	[DataInsert] [datetime] NULL,
 CONSTRAINT [PK_Profissao] PRIMARY KEY CLUSTERED 
(
	[ProfissaoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [EST].[Subcategoria](
	[Codigo] [int] IDENTITY(1,1) NOT NULL,
	[CodigoCategoria] [int] NOT NULL,
	[Descricao] [varchar](max) NOT NULL,
	[DataInsert] [datetime] NOT NULL,
 CONSTRAINT [PK_Subcategoria] PRIMARY KEY CLUSTERED 
(
	[Codigo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [EST].[Categoria] ADD  DEFAULT (getdate()) FOR [DataInsert]
GO
ALTER TABLE [Geral].[Cliente] ADD  DEFAULT ('F') FOR [TipoPessoa]
GO
ALTER TABLE [Geral].[Cliente] ADD  DEFAULT ((1)) FOR [Ativo]
GO
ALTER TABLE [Geral].[Cliente] ADD  DEFAULT (getdate()) FOR [DataInclusao]
GO
ALTER TABLE [RH].[Departamento] ADD  DEFAULT (getdate()) FOR [DataInsert]
GO
ALTER TABLE [RH].[Funcionario] ADD  DEFAULT (getdate()) FOR [DataAdmissao]
GO
ALTER TABLE [Geral].[InstituicaoBancaria] ADD  DEFAULT (getdate()) FOR [DataInsert]
GO
ALTER TABLE [Geral].[Municipio] ADD  DEFAULT (getdate()) FOR [DataInclusao]
GO
ALTER TABLE [Geral].[Pais] ADD  DEFAULT (getdate()) FOR [DataInsert]
GO
ALTER TABLE [EST].[Produto] ADD  DEFAULT (getdate()) FOR [DataInsert]
GO
ALTER TABLE [RH].[Profissao] ADD  DEFAULT (getdate()) FOR [DataInsert]
GO
ALTER TABLE [EST].[Subcategoria] ADD  DEFAULT (getdate()) FOR [DataInsert]
GO
ALTER TABLE [Geral].[Municipio]  WITH CHECK ADD  CONSTRAINT [FK_Municipio_Estado] FOREIGN KEY([CodigoUF])
REFERENCES [Geral].[Estado] ([CodigoUF])
GO
ALTER TABLE [Geral].[Municipio] CHECK CONSTRAINT [FK_Municipio_Estado]
GO
ALTER TABLE [EST].[Produto]  WITH CHECK ADD  CONSTRAINT [FK_Produto_Subcategoria] FOREIGN KEY([CodigoSubcategoria])
REFERENCES [EST].[Subcategoria] ([Codigo])
GO
ALTER TABLE [EST].[Produto] CHECK CONSTRAINT [FK_Produto_Subcategoria]
GO
ALTER TABLE [EST].[Subcategoria]  WITH CHECK ADD  CONSTRAINT [FK_SubCategoria_Categoria] FOREIGN KEY([CodigoCategoria])
REFERENCES [EST].[Categoria] ([Codigo])
GO
ALTER TABLE [EST].[Subcategoria] CHECK CONSTRAINT [FK_SubCategoria_Categoria]
GO
